version: '3.5'

services:

  api:
    build:
      context: ./destacame_django
    restart: always
    command: "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - postgres-db

    ports:
    - 9020:8000

  front:
    build:
      context: ./destacame_vue
    restart: always
    command: "npm run serve"
    depends_on:
      - api

    ports:
      - 9030:8080


  postgres-db:
    image: postgres:10.15
    restart: always
    environment:
      POSTGRES_PASSWORD: 'destacame'
      POSTGRES_USER: 'destacame'
      POSTGRES_DB: 'destacame'
    volumes:
    - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
    driver: local
