# Generated by Django 3.1.4 on 2020-12-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ('name',), 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('name',)},
        ),
    ]
